config/routes.rb
Rails.application.routes.draw do
  resources :notes
  root to: redirect("notes")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :body, presence: true

  def self.search_by_title(keywords)
    where title: keywords
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  def index
    filters = params[:filters]&.to_unsafe_h&.symbolize_keys
    if filters && filters[:title].present?
      @notes = Note.search_by_title(filters[:title])
    else
      @notes = Note.all
    end

    @notes
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to notes_path, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_as_localtime(datetime)
    datetime.strftime "%d/%b/%Y"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My note collection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <div class="brand-logo center">
            My note collection
          </div>
        </div>
      </nav>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h5>

      <ul>
        <% note.errors.each do |error| %>
          <li>&bull; <%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row" style="margin-top: 7mm">
    <div class="input-field col s12">
      <%= form.text_field :title, autofocus: true %>
      <%= form.label :title %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= form.text_field :body, class: 'materialize-textarea' %>
      <%= form.label :body %>
    </div>
  </div>

  <div class="row">
    <div class="col s12 right-align">
      <button class="btn-flat waves-effect waves-light" type="submit">
        <%= material_icon.send %>
      </button>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <%= form_for :filters, html: { class: 'input-field col s12' }, method: 'get' do |f| %>
    <%= material_icon.search.css_class('prefix') %>
    <%= f.text_field :title, autofocus: true, placeholder: 'Search by title', value: params.dig(:filters, :title) %>
  <% end %>

  <% @notes.each do |note| %>
    <%= link_to notes_path do %>
      <div class="col s6">
        <div class="card">
          <div class="card-content black-text">
            <span class="card-title">
              <%= note.title %>
              <span style="font-size: 50%">
                <%= format_as_localtime note.created_at %>
              </span>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="fixed-action-btn">
  <%= link_to new_note_path, title: 'New note', class: 'btn-floating btn-large pulse disabled' do %>
    <%= material_icon.add %>
  <% end %>
</div>

app/views/notes/new.html.erb
<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          <%= @note.title %>
          <span class="right" style="font-size: 50%">
            <%= format_as_localtime @note.created_at %>
          </span>
        </span>
        <p><%= @note.body %></p>
      </div>
      <div class="card-action">
        <%= link_to @note, title: 'Delete', method: :delete, data: { confirm: 'Are you sure?' }, class: 'black-text' do %>
          <%= material_icon.mode_edit %>
        <% end %>

        <%= link_to edit_note_path(@note), title: 'Edit', class: 'black-text right' do %>
          <%= material_icon.delete %>
        <% end %>
      </div>
    </div>
  </div>
</div>